name: stepOut
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_clean_architecture:
  flutter_calendar_carousel:
  dio:
  internet_connection_checker:
  fluttertoast: ^8.2.1
  dartz:
  pretty_dio_logger: ^1.3.1
  shared_preferences:
  get_it:
  http:
  firebase_messaging: ^14.7.4
  provider:
  flutter_staggered_animations:
  connectivity:
  image_picker:
  cached_network_image:
  flutter_styled_toast:
  flutter_animated_dialog:
  flutter_animate:
  url_launcher: ^6.1.11
  readmore:
  flutter_svg:
  flutter_local_notifications: ^16.1.0
  flutter_form_builder:
  equatable:
  pin_code_fields:
  cupertino_icons: ^1.0.2
  modal_bottom_sheet: ^3.0.0-pre
  shimmer:
  carousel_slider:
  firebase_auth: ^4.4.0
  whatsapp_unilink: ^2.1.0
  firebase_dynamic_links: ^5.1.0
  firebase_analytics: ^10.2.1
  flutter_native_splash: ^2.2.0+1
  syncfusion_flutter_charts: ^21.1.41
  flutter_typeahead:
  geolocator_platform_interface:
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.8
  map_launcher: ^2.5.0+1
  flutter_polyline_points:
  country_picker: ^2.0.20
  flag:
  flutter_spinkit:
  app_settings: ^5.1.1
  substring_highlight: ^1.0.33
  motion_toast: ^2.6.8
  flutter_inappwebview:
      git:
         url: https://github.com/Estrelio/flutter_inappwebview.git
         ref: fix-xcode-17
  flutter_zoom_drawer: ^3.1.1
  flutter_widget_from_html: ^0.14.3
  file_picker: ^6.0.0
  permission_handler: ^10.4.3
  path_provider: ^2.0.15
  firebase_core: ^2.22.0
  rxdart: ^0.26.0
  scroll_to_index: ^3.0.1
  should_rebuild: ^1.0.1
  syncfusion_flutter_sliders: ^21.2.10



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/svgs/
    - assets/images/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/en/Roboto-Thin.ttf
          weight: 300
        - asset: assets/fonts/en/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/en/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/en/Roboto-Light.ttf
          weight: 600
        - asset: assets/fonts/en/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/en/Roboto-Black.ttf
          weight: 800

    - family: ar
      fonts:
        - asset: assets/fonts/ar/ExpoArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/ar/ExpoArabic-regular.ttf
          weight: 400
        - asset: assets/fonts/ar/ExpoArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/ar/Expo Arabic SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ar/Expo Arabic Bold.ttf
          weight: 700