name: Build and Send APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6' # Adjust to your Flutter version

      - name: Build APK
        run: |
          flutter clean
          flutter build apk --release

      - name: Upload APK Artifact
        id: upload_apk
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Artifact to Transfer.sh
        id: upload_artifact
        run: |
          UPLOAD_URL=$(curl --upload-file ${{ github.workspace }}/build/app/outputs/flutter-apk/app-release.apk https://transfer.sh/app-release.apk --max-time 300 --retry 5)
          echo "Artifact uploaded to: $UPLOAD_URL"
          echo "GITHUB_STATE=upload_url=$UPLOAD_URL" >> $GITHUB_ENV

      - name: Send APK URL via Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        run: |
          MESSAGE="Here's the Step Out APK: $UPLOAD_URL"
          curl -s "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" -d "chat_id=$TELEGRAM_CHAT_ID" -d "text=$MESSAGE"
